### ISSUE TITLE
Credentials should *not* be stored in plaintext, much less synced into GitHub as a public gist

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ultram4rine/sqltools-clickhouse-driver#482]
At the moment, this (and several other drivers) store creds in plaintext — and worse, when Settings Sync is enabled, they can get sync'd to a public GitHub gist.

(See: mtxr/vscode-sqltools#210, mtxr/vscode-sqltools#479, mtxr/vscode-sqltools#927 …)

There's a new-ish API upstream that you can use for this, to properly behave as an AuthenticationProvider; see mtxr/vscode-sqltools#1066 for an example implementation.

This is pretty critical for us, ugh; but please don't take that too aggressively — I recognize this is a best-effort FOSS project. Take care of yourself. 💜

**Comment by ultram4rine** [comment]
Hi @ELLIOTTCABLE, I hope this will be fixed in #515.

Btw, vscode has built-in settings-sync feature, so you doesn't need to use extension that pushes them to Gist.

Btw2, my gist was private:
![image](https://github.com/ultram4rine/sqltools-clickhouse-driver/assets/42237599/ddd361c7-d0bc-4837-be95-78dcf3a29cf8)
